### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by ScottMunroMS** [dominikduda/vim_timebox#1]
Was looking in the autoload's .vim file and I see a bunch of system calls like `touch` and `tail` which don't have native windows equivalents.

I think this is why when I try and use this cool plugin in GVim on windows, nothing happens :(

**Comment by dominikduda** [comment]
Sorry, I don't plan windows support.

This plugin was supposed to be a small fast project utilizing bash and Unix file system.

Fell free to PR windows support if you like
